### ISSUE TITLE
awesome work - and suggestion 

### ISSUE THREAD

**Issue by johndpope** [davedelong/DDHotKey#8]
Hi Dave,

Thanks for your efforts - I would like to display the hotkey keycode as a string and modifier key as a symbol.  I guess this would be something of use to others. Will see if I can fix this and submit a PR.

![screen shot 2015-03-08 at 2 11 04 pm](https://cloud.githubusercontent.com/assets/289994/6544291/fa3ab4aa-c59c-11e4-9131-19659df20274.png)

**Comment by davedelong** [comment]
Hey @johndpope,

I think the `DDStringFromKeyCode()` function will do what you're looking for

**Comment by johndpope** [comment]
great thx.
